"""Knowledge-base models.

A ``KBDocument`` is a source article (an FAQ entry, a policy page, a troubleshooting
guide). It is split into ``KBChunk`` rows, each of which stores:

* ``content``      — the chunk text (used to build the answer + citations)
* ``embedding``    — a pgvector column for **semantic** search (cosine distance)
* ``content_tsv``  — a Postgres ``tsvector`` for **keyword** full-text search

Holding both signals on the same row is what makes hybrid retrieval (semantic +
keyword, fused with RRF) a single, index-backed query set.
"""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID, uuid4

from pgvector.sqlalchemy import Vector
from sqlalchemy import Column, Computed, Index, Text
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlmodel import Field, SQLModel

from app.core.config import settings


class KBDocument(SQLModel, table=True):
    """A source knowledge-base article."""

    __tablename__ = "kb_documents"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    title: str = Field(index=True)
    source: str = Field(description="Origin file / URL of the article.")
    category: str = Field(default="general", index=True)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class KBChunk(SQLModel, table=True):
    """A retrievable chunk of a KB document."""

    __tablename__ = "kb_chunks"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    document_id: UUID = Field(foreign_key="kb_documents.id", index=True)
    chunk_index: int = 0
    content: str = Field(sa_column=Column(Text, nullable=False))

    # Semantic search vector. Dimension must match settings.embedding_dim.
    embedding: list[float] = Field(
        sa_column=Column(Vector(settings.embedding_dim), nullable=False)
    )

    # Keyword search vector, generated by Postgres from ``content``.
    content_tsv: str | None = Field(
        default=None,
        sa_column=Column(
            TSVECTOR,
            Computed("to_tsvector('english', content)", persisted=True),
        ),
    )

    __table_args__ = (
        # GIN index for fast full-text (keyword) search.
        Index("ix_kb_chunks_tsv", "content_tsv", postgresql_using="gin"),
        # IVFFlat index for approximate nearest-neighbour semantic search.
        Index(
            "ix_kb_chunks_embedding",
            "embedding",
            postgresql_using="ivfflat",
            postgresql_with={"lists": 100},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )
